version: '3.1'

services:
  prometheus:
    image: prom/prometheus:v2.4.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - $PWD/etc/prometheus:/etc/prometheus/
      - $PWD/data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:5.3.2
    container_name: grafana
    restart: always
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=install"
    ports:
      - 3000:3000
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
    links:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v0.15.2
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - $PWD/etc/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  blackbox:
    image: prom/blackbox-exporter:v0.12.0
    container_name: blackbox
    restart: always
    ports:
      - 9115:9115
    volumes:
      - $PWD/etc/blackbox:/etc/blackbox_exporter

  pushgateway:
    image: prom/pushgateway:v0.5.2
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
