version: '3.1'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=install"
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - $PWD/etc/prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - $PWD/etc/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: always
    ports:
      - 9115:9115
    volumes:
      - $PWD/etc/blackbox:/etc/blackbox_exporter

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodexporter
    restart: always
    ports:
      - 9100:9100

volumes:
  prometheus-data:
  grafana-data:
