version: '3.1'

services:
  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    restart: always
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=install"
    ports:
      - 3000:3000
    networks:
      - prom
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.31.0-rc.0
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - prom
    volumes:
      - $PWD/etc/prometheus:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - 9093:9093
    networks:
      - prom
    volumes:
      - $PWD/etc/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: always
    ports:
      - 9115:9115
    networks:
      - prom
    volumes:
      - $PWD/etc/blackbox:/etc/blackbox_exporter

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
    networks:
      - prom

volumes:
  prometheus-data:
  grafana-data:

networks:
  prom:
    driver: bridge
