global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"

scrape_configs:

  # Picks up any endpoint with METRICS
  - job_name: 'consul_sd_springboot_metrics'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
         - server: 'localhost:8500'
           datacenter: 'eastus2'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,SPRINGBOOT_METRICS,.*
        action: 'keep'
        target_label: metric
      - source_labels: [__meta_consul_tags]
        regex: '.*,(dev|prd|qat|prd),.*'
        replacement: '${1}'
        target_label: env
      - source_labels: [__meta_consul_service]
        target_label: service

  - job_name: 'nginx-waf'
    static_configs:
      - targets: ['172.31.31.11:9913']

  - job_name: 'kafka-jmx'
    scrape_interval: 180s
    scrape_timeout: 180s
    static_configs:
      - targets: ['172.31.29.158:17100']

  - job_name: 'cadvisor'
    static_configs:
          - targets: ['172.31.29.152:9090']

  - job_name: 'nginx-vsts'
    static_configs:
          - targets: ['172.31.31.11:9100']

  - job_name: 'wmi-exporter'
    static_configs:
          - targets: ['172.31.241.68:9182']

  - job_name: 'blackbox_tcp_check'
    metrics_path: /probe
    params:
      module: [tcp_connect]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - localhost 9090

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox exporter

  - job_name: 'blackbox_http_check'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://localhost:9090

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox exporter

  - job_name: 'mysql-check'
    scrape_interval: 15s
    static_configs:
      - targets:
        - '172.31.29.15:9104'
    params:
      collect[]:
        - global_status

  - job_name: 'blackbox_dns'
    metrics_path: /probe
    params:
      module: [dns_rp_consul]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 172.31.29.100

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Blackbox exporter
